version: "3.3"

services:

  db:
    container_name: csu-image-db
    build:
      context: ./docker/dev
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
